import { HeaderOnlyLogo } from '@/components/HeaderOnlyLogo';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function EventDasboardRoot({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>
    <HeaderOnlyLogo />
  {children}
  </>;
}
