import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Dashboard Event List',
  description: 'Generated by create next app',
};

export default function DashboardEventListRoot({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>
  {children}
  </>;
}
